version: '3.9'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - migrator
  migrator:
    build: 
      dockerfile: ./Diesel.Dockerfile
    links:
      - db
    command: ["sh","wait_for_postgres.sh","diesel setup"]
  db:
    image: postgres
    ports:
      - "3000:5432"
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: dbexample